import { createApp } from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
import pinia from "@/store/pinia";
import moment from "moment";
import momentTimeZone from "moment-timezone";
import time from "@/directive/time";
import sliceText from "@/directive/sliceText";
import sliceAccount from "@/directive/sliceAccount";
import slicePixKey from "@/directive/slicePixKey";
import i18n from "./utils/i18n";
import { useLanguage } from "@/store/languageStore";
import AudioPlayer from "@liripeng/vue-audio-player";
import * as PIXI from "pixi.js";
import price from "@/directive/price";
import VueCountdown from "@chenfengyuan/vue-countdown";
import { ElProgress } from "element-plus";
import "element-plus/dist/index.css";

PIXI.utils.skipHello();
const app = createApp(App);
const languageStore = useLanguage();
const { getCurLang } = languageStore;
getCurLang();
app.use(router);
app.use(pinia);
app.use(i18n);
app.use(moment);
app.use(momentTimeZone);
app.use(AudioPlayer);
app.use(ElProgress);
app.mount("#app");
app.directive("price", price);
app.directive("time", time);
app.directive("sliceText", sliceText);
app.directive("sliceAccount", sliceAccount);
app.directive("slicePixKey", slicePixKey);
app.component(VueCountdown.name, VueCountdown);
